# These characters will only work in single player and
# servers under the SahilP family.

# Originally created by Stigma and Mr.Smoothy
# Extended by fans

# ba_meta require api 8

import babase
import bauiv1 as bui
import bascenev1 as bs
from bascenev1lib.actor.spazappearance import Appearance


CHARACTERS = {
    "SahilP > Shraddha": {
        "color_texture": "pixieColor",
        "color_mask_texture": "pixieColorMask",
        "icon_texture": "pixieIcon",
        "icon_mask_texture": "pixieIconColorMask",
        "head_mesh": "pixieHead",
        "torso_mesh": "pixieTorso",
        "pelvis_mesh": "pixiePelvis",
        "upper_arm_mesh": "pixieUpperArm",
        "forearm_mesh": "pixieForeArm",
        "hand_mesh": "pixieHand",
        "upper_leg_mesh": "pixieUpperLeg",
        "lower_leg_mesh": "pixieLowerLeg",
        "toes_mesh": "pixieToes",
        "attack_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "jump_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "impact_sounds": ["pixieHit1", "pixieHit2"],
        "death_sounds": ["pixieDeath"],
        "pickup_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "fall_sounds": ["pixieFall"],
        "style": "female",
    },

    "SahilP > Zubi": {
        "color_texture": "wizardColor",
        "color_mask_texture": "wizardColorMask",
        "icon_texture": "agentIcon",
        "icon_mask_texture": "agentIconColorMask",
        "head_mesh": "wizardHead",
        "torso_mesh": "agentTorso",
        "pelvis_mesh": "agentPelvis",
        "upper_arm_mesh": "agentUpperArm",
        "forearm_mesh": "agentForeArm",
        "hand_mesh": "agentHand",
        "upper_leg_mesh": "agentUpperLeg",
        "lower_leg_mesh": "agentLowerLeg",
        "toes_mesh": "agentToes",
        "attack_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "jump_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "impact_sounds": ["agentHit1", "agentHit2"],
        "death_sounds": ["agentDeath"],
        "pickup_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "fall_sounds": ["agentFall"],
        "style": "spaz",
    },

    "SahilP > Sonu": {
        "color_texture": "agentColor",
        "color_mask_texture": "agentColorMask",
        "icon_texture": "agentIcon",
        "icon_mask_texture": "agentIconColorMask",
        "head_mesh": "agentHead",
        "torso_mesh": "agentTorso",
        "pelvis_mesh": "agentPelvis",
        "upper_arm_mesh": "agentUpperArm",
        "forearm_mesh": "agentForeArm",
        "hand_mesh": "agentHand",
        "upper_leg_mesh": "agentUpperLeg",
        "lower_leg_mesh": "agentLowerLeg",
        "toes_mesh": "agentToes",
        "attack_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "jump_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "impact_sounds": ["agentHit1", "agentHit2"],
        "death_sounds": ["agentDeath"],
        "pickup_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "fall_sounds": ["agentFall"],
        "style": "pixie",
    },

    "SahilP > MrIce": {
        "color_texture": "explosion",
        "color_mask_texture": "bearColorMask",
        "icon_texture": "bonesIcon",
        "icon_mask_texture": "logo",
        "head_mesh": "frostyHead",
        "torso_mesh": "kronkTorso",
        "pelvis_mesh": "cyborgPelvis",
        "upper_arm_mesh": "frostyUpperArm",
        "forearm_mesh": "cyborgForeArm",
        "hand_mesh": "bearHand",
        "upper_leg_mesh": "cyborgUpperLeg",
        "lower_leg_mesh": "bonesLowerLeg",
        "toes_mesh": "bonesToes",
        "attack_sounds": ["powerdown01"],
        "jump_sounds": ["powerup01"],
        "impact_sounds": ["powerdown01"],
        "death_sounds": ["powerdown01"],
        "pickup_sounds": ["ticking"],
        "fall_sounds": ["powerdown01"],
        "style": "bear",
    },

    "SahilP > TurtleZoe": {
        "color_texture": "zoeColor",
        "color_mask_texture": "zoeColorMask",
        "icon_texture": "zoeIcon",
        "icon_mask_texture": "zoeIconColorMask",
        "head_mesh": "zoeHead",
        "torso_mesh": "bearTorso",
        "pelvis_mesh": "bearPelvis",
        "upper_arm_mesh": "bearUpperArm",
        "forearm_mesh": "bearForeArm",
        "hand_mesh": "bearHand",
        "upper_leg_mesh": "bearUpperLeg",
        "lower_leg_mesh": "bearLowerLeg",
        "toes_mesh": "bearToes",
        "jump_sounds": ["zoeJump01", "zoeJump02", "zoeJump03"],
        "attack_sounds": ["zoeAttack01", "zoeAttack02", "zoeAttack03", "zoeAttack04"],
        "impact_sounds": ["zoeImpact01", "zoeImpact02", "zoeImpact03", "zoeImpact04"],
        "death_sounds": ["zoeDeath01"],
        "pickup_sounds": ["zoePickup01"],
        "fall_sounds": ["zoeFall01"],
        "style": "female",
    },

    "SahilP > CozyFrosty": {
        "color_texture": "frostyColor",
        "color_mask_texture": "jackColorMask",
        "head_mesh": "frostyHead",
        "hand_mesh": "frostyHand",
        "torso_mesh": "frostyTorso",
        "pelvis_mesh": "frostyPelvis",
        "upper_arm_mesh": "frostyUpperArm",
        "forearm_mesh": "frostyForeArm",
        "upper_leg_mesh": "frostyUpperLeg",
        "lower_leg_mesh": "frostyLowerLeg",
        "toes_mesh": "frostyToes",
        "jump_sounds": ["frosty01", "frosty02", "frosty03", "frosty04", "frosty05"],
        "attack_sounds": ["frosty01", "frosty02", "frosty03", "frosty05", "frosty05"],
        "impact_sounds": ["frostyHit01", "frostyHit02", "frostyHit03"],
        "death_sounds": ["frostyDeath"],
        "pickup_sounds": ["frosty01", "frosty02", "frosty03", "frosty04", "frosty05"],
        "fall_sounds": ["frostyFall"],
        "icon_texture": "frostyIcon",
        "icon_mask_texture": "jackIconColorMask",
        "style": "frosty",
    },

    "SahilP > CrystalPixel": {
        "color_texture": "pixieColor",
        "color_mask_texture": "zoeColorMask",
        "head_mesh": "pixieHead",
        "hand_mesh": "pixieHand",
        "torso_mesh": "pixieTorso",
        "pelvis_mesh": "pixiePelvis",
        "upper_arm_mesh": "pixieUpperArm",
        "forearm_mesh": "pixieForeArm",
        "upper_leg_mesh": "pixieUpperLeg",
        "lower_leg_mesh": "pixieLowerLeg",
        "toes_mesh": "pixieToes",
        "jump_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "attack_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "impact_sounds": ["pixieHit1", "pixieHit2"],
        "death_sounds": ["pixieDeath"],
        "pickup_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "fall_sounds": ["pixieFall"],
        "icon_texture": "pixieIcon",
        "icon_mask_texture": "zoeIconColorMask",
        "style": "pixie",
    },

    "SahilP > GentleAgent": {
        "color_texture": "agentColor",
        "color_mask_texture": "pixieColorMask",
        "head_mesh": "agentHead",
        "hand_mesh": "agentHand",
        "torso_mesh": "agentTorso",
        "pelvis_mesh": "agentPelvis",
        "upper_arm_mesh": "agentUpperArm",
        "forearm_mesh": "agentForeArm",
        "upper_leg_mesh": "agentUpperLeg",
        "lower_leg_mesh": "agentLowerLeg",
        "toes_mesh": "agentToes",
        "jump_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "attack_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "impact_sounds": ["agentHit1", "agentHit2"],
        "death_sounds": ["agentDeath"],
        "pickup_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "fall_sounds": ["agentFall"],
        "icon_texture": "agentIcon",
        "icon_mask_texture": "agentIconColorMask",
        "style": "agent",
    },

    "SahilP > SpazKnight": {
        "color_texture": "neoSpazColor",
        "color_mask_texture": "neoSpazColorMask",
        "head_mesh": "neoSpazHead",
        "hand_mesh": "penguinHand",
        "torso_mesh": "bunnyTorso",
        "pelvis_mesh": "neoSpazPelvis",
        "upper_arm_mesh": "wrestlerUpperArm",
        "forearm_mesh": "neoSpazForeArm",
        "upper_leg_mesh": "aliUpperLeg",
        "lower_leg_mesh": "zoeLowerLeg",
        "toes_mesh": "wizardToes",
        "jump_sounds": ["spazJump01", "spazJump02", "spazJump03", "spazJump04"],
        "attack_sounds": ["spazAttack01", "spazAttack02", "spazAttack03", "spazAttack04"],
        "impact_sounds": ["spazImpact01", "spazImpact02", "spazImpact03", "spazImpact04"],
        "death_sounds": ["spazDeath01"],
        "pickup_sounds": ["spazPickup01"],
        "fall_sounds": ["spazFall01"],
        "icon_texture": "neoSpazIcon",
        "icon_mask_texture": "zoeIconColorMask",
        "style": "female",
    },

    "SahilP > Axer": {
        "color_texture": "agentColor",
        "color_mask_texture": "agentColorMask",
        "head_mesh": "agentHead",
        "hand_mesh": "agentHand",
        "torso_mesh": "bonesTorso",
        "pelvis_mesh": "agentPelvis",
        "upper_arm_mesh": "ninjaUpperArm",
        "forearm_mesh": "cyborgForeArm",
        "upper_leg_mesh": "agentUpperLeg",
        "lower_leg_mesh": "agentLowerLeg",
        "toes_mesh": "agentToes",
        "jump_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "attack_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "impact_sounds": ["agentHit1", "agentHit2"],
        "death_sounds": ["agentDeath"],
        "pickup_sounds": ["agent1", "agent2", "agent3", "agent4"],
        "fall_sounds": ["agentFall"],
        "icon_texture": "agentIcon",
        "icon_mask_texture": "agentIconColorMask",
        "style": "agent",
    },

    "SahilP > CheergirlZoe": {
        "color_texture": "zoeColor",
        "color_mask_texture": "zoeColorMask",
        "head_mesh": "zoeHead",
        "hand_mesh": "kronkHand",
        "torso_mesh": "neoSpazTorso",
        "pelvis_mesh": "pixiePelvis",
        "upper_arm_mesh": "zoeUpperArm",
        "forearm_mesh": "agentForeArm",
        "upper_leg_mesh": "neoSpazUpperLeg",
        "lower_leg_mesh": "frostyLowerLeg",
        "toes_mesh": "bearToes",
        "jump_sounds": ["zoeJump01", "zoeJump02", "zoeJump03"],
        "attack_sounds": ["zoeAttack01", "zoeAttack02", "zoeAttack03"],
        "impact_sounds": ["zoeImpact01", "zoeImpact02", "zoeImpact03", "zoeImpact04"],
        "death_sounds": ["zoeDeath01"],
        "pickup_sounds": ["zoePickup01"],
        "fall_sounds": ["zoeFall01"],
        "icon_texture": "zoeIcon",
        "icon_mask_texture": "zoeIconColorMask",
        "style": "female",
    },

    "SahilP > Pixent": {
        "color_texture": "agentColor",
        "color_mask_texture": "melColorMask",
        "head_mesh": "pixieHead",
        "hand_mesh": "agentHand",
        "torso_mesh": "agentTorso",
        "pelvis_mesh": "agentPelvis",
        "upper_arm_mesh": "cyborgUpperArm",
        "forearm_mesh": "bonesForeArm",
        "upper_leg_mesh": "frostyUpperLeg",
        "lower_leg_mesh": "agentLowerLeg",
        "toes_mesh": "agentToes",
        "jump_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "attack_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "impact_sounds": ["pixieHit1", "pixieHit2"],
        "death_sounds": ["pixieDeath"],
        "pickup_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "fall_sounds": ["pixieFall"],
        "icon_texture": "pixieIcon",
        "icon_mask_texture": "pixieIconColorMask",
        "style": "agent",
    },

    "SahilP > She-Pascal": {
        "color_texture": "penguinColor",
        "color_mask_texture": "penguinColorMask",
        "head_mesh": "penguinHead",
        "hand_mesh": "penguinHand",
        "torso_mesh": "penguinTorso",
        "pelvis_mesh": "neoSpazPelvis",
        "upper_arm_mesh": "penguinUpperArm",
        "forearm_mesh": "penguinForeArm",
        "upper_leg_mesh": "penguinUpperLeg",
        "lower_leg_mesh": "neoSpazLowerLeg",
        "toes_mesh": "neoSpazToes",
        "jump_sounds": ["penguin1", "penguin2", "penguin3", "penguin4"],
        "attack_sounds": ["penguin1", "penguin2", "penguin3", "penguin4"],
        "impact_sounds": ["penguinHit1", "penguinHit2"],
        "death_sounds": ["penguinDeath"],
        "pickup_sounds": ["penguin1", "penguin2", "penguin3", "penguin4"],
        "fall_sounds": ["penguinFall"],
        "icon_texture": "penguinIcon",
        "icon_mask_texture": "penguinIconColorMask",
        "style": "pixie",
    },

    "SahilP > Skullster": {
        "color_texture": "bonesColor",
        "color_mask_texture": "zoeColorMask",
        "head_mesh": "bonesHead",
        "hand_mesh": "neoSpazHand",
        "torso_mesh": "ninjaTorso",
        "pelvis_mesh": "zoePelvis",
        "upper_arm_mesh": "agentUpperArm",
        "forearm_mesh": "neoSpazForeArm",
        "upper_leg_mesh": "neoSpazUpperLeg",
        "lower_leg_mesh": "pixieLowerLeg",
        "toes_mesh": "cyborgToes",
        "jump_sounds": ["bones1", "bones2", "bones3"],
        "attack_sounds": ["bones1", "bones2", "bones3"],
        "impact_sounds": ["bones1", "bones2", "bones3"],
        "death_sounds": ["bonesDeath"],
        "pickup_sounds": ["bones1", "bones2", "bones3"],
        "fall_sounds": ["bonesFall"],
        "icon_texture": "bonesIcon",
        "icon_mask_texture": "zoeIconColorMask",
        "style": "frosty",
    },

    "SahilP > Corona": {
        "color_texture": "impactBombColorLit",
        "color_mask_texture": "crossOutMask",
        "head_mesh": "impactBomb",
        "hand_mesh": "cyborgHand",
        "torso_mesh": "wizardTorso",
        "pelvis_mesh": "hairTuft4",
        "upper_arm_mesh": "ninjaUpperArm",
        "forearm_mesh": "cyborgForeArm",
        "upper_leg_mesh": "cyborgUpperLeg",
        "lower_leg_mesh": "pixieLowerLeg",
        "toes_mesh": "cyborgToes",
        "jump_sounds": ["jack01", "jack02", "jack03", "jack04", "jack05", "jack06"],
        "attack_sounds": ["jack01", "jack02", "jack03", "jack04", "jack05", "jack06"],
        "impact_sounds": ["jackHit01", "jackHit02", "jackHit03", "jackHit04", "jackHit05"],
        "death_sounds": ["jackDeath01"],
        "pickup_sounds": ["jack01", "jack02", "jack03", "jack04", "jack05", "jack06"],
        "fall_sounds": ["jackFall01"],
        "icon_texture": "impactBombColorLit",
        "icon_mask_texture": "jackIconColorMask",
        "style": "pirate",
    },

    "SahilP > Hazel": {
        "color_texture": "pixieColor",
        "color_mask_texture": "zoeColorMask",
        "head_mesh": "pixieHead",
        "hand_mesh": "bunnyHand",
        "torso_mesh": "bunnyTorso",
        "pelvis_mesh": "bunnyPelvis",
        "upper_arm_mesh": "zoeUpperArm",
        "forearm_mesh": "zoeForeArm",
        "upper_leg_mesh": "zoeUpperLeg",
        "lower_leg_mesh": "zoeLowerLeg",
        "toes_mesh": "zoeToes",
        "jump_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "attack_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "impact_sounds": ["pixieHit1", "pixieHit2"],
        "death_sounds": ["pixieDeath"],
        "pickup_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "fall_sounds": ["pixieFall"],
        "icon_texture": "pixieIcon",
        "icon_mask_texture": "pixieIconColorMask",
        "style": "pixie",
    },

    "SahilP > MentozZindagi": {
        "color_texture": "powerupCurse",
        "color_mask_texture": "frostyColorMask",
        "head_mesh": "bomb",
        "hand_mesh": "jackHand",
        "torso_mesh": "pixieTorso",
        "pelvis_mesh": "bunnyPelvis",
        "upper_arm_mesh": "bearUpperArm",
        "forearm_mesh": "frostyForeArm",
        "upper_leg_mesh": "jackUpperLeg",
        "lower_leg_mesh": "ninjaLowerLeg",
        "toes_mesh": "neoSpazToes",
        "jump_sounds": ["bones1", "bones2", "bones3"],
        "attack_sounds": ["spazAttack01", "spazAttack02", "spazAttack03", "spazAttack04"],
        "impact_sounds": ["bones1", "bones2", "bones3"],
        "death_sounds": ["spazDeath01"],
        "pickup_sounds": ["spazPickup01"],
        "fall_sounds": ["spazFall01"],
        "icon_texture": "bonesIcon",
        "icon_mask_texture": "logo",
        "style": "agent",
    },

    "SahilP > GhostOfSpaz": {
        "color_texture": "powerupCurse",
        "color_mask_texture": "bunnyColorMask",
        "head_mesh": "neoSpazHead",
        "hand_mesh": "penguinHand",
        "torso_mesh": "zoeTorso",
        "pelvis_mesh": "cyborgPelvis",
        "upper_arm_mesh": "frostyUpperArm",
        "forearm_mesh": "kronkForeArm",
        "upper_leg_mesh": "bonesUpperLeg",
        "lower_leg_mesh": "melLowerLeg",
        "toes_mesh": "neoSpazToes",
        "jump_sounds": ["cyborg1", "cyborg2", "cyborg3", "cyborg4"],
        "attack_sounds": ["cyborg1", "cyborg2", "cyborg3", "cyborg4"],
        "impact_sounds": ["cyborgHit1", "cyborgHit2"],
        "death_sounds": ["cyborgDeath"],
        "pickup_sounds": ["cyborg1", "cyborg2", "cyborg3", "cyborg4"],
        "fall_sounds": ["cyborgFall"],
        "icon_texture": "cyborgIcon",
        "icon_mask_texture": "neoSpazIconColorMask",
        "style": "pixie",
    },

    "SahilP > Werewolf": {
        "color_texture": "bearColor",
        "color_mask_texture": "cyborgColorMask",
        "head_mesh": "bearHead",
        "hand_mesh": "bunnyHand",
        "torso_mesh": "ninjaTorso",
        "pelvis_mesh": "kronkPelvis",
        "upper_arm_mesh": "neoSpazUpperArm",
        "forearm_mesh": "santaForeArm",
        "upper_leg_mesh": "aliUpperLeg",
        "lower_leg_mesh": "neoSpazLowerLeg",
        "toes_mesh": "zoeToes",
        "jump_sounds": ["bear1", "bear2", "bear3", "bear4", "kronk1", "kronk2", "kronk3", "kronk4", "kronk5", "kronk6", "kronk7", "kronk8", "kronk9", "kronk10"],
        "attack_sounds": ["bear1", "bear2", "bear3", "bear4", "kronk1", "kronk2", "kronk3", "kronk4", "kronk5", "kronk6", "kronk7", "kronk8", "kronk9", "kronk10"],
        "impact_sounds": ["bearHit1", "bearHit2", "kronk1", "kronk2", "kronk3", "kronk4", "kronk5", "kronk6", "kronk7", "kronk8", "kronk9", "kronk10"],
        "death_sounds": ["bearDeath", "kronkDeath"],
        "pickup_sounds": ["bear1", "bear2", "bear3", "bear4", "kronk1", "kronk2", "kronk3", "kronk4", "kronk5", "kronk6", "kronk7", "kronk8", "kronk9", "kronk10"],
        "fall_sounds": ["bearFall", "kronkFall"],
        "icon_texture": "bearIcon",
        "icon_mask_texture": "bearIconColorMask",
        "style": "kronk",
    },

    "SahilP > BandedPixie2": {
        "color_texture": "pixieColor",
        "color_mask_texture": "pixieColorMask",
        "head_mesh": "pixieHead",
        "hand_mesh": "frostyHand",
        "torso_mesh": "zoeTorso",
        "pelvis_mesh": "pixiePelvis",
        "upper_arm_mesh": "pixieUpperArm",
        "forearm_mesh": "ninjaForeArm",
        "upper_leg_mesh": "pixieUpperLeg",
        "lower_leg_mesh": "frostyLowerLeg",
        "toes_mesh": "pixieToes",
        "jump_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "attack_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "impact_sounds": ["pixieHit1", "pixieHit2"],
        "death_sounds": ["pixieDeath"],
        "pickup_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "fall_sounds": ["pixieFall"],
        "icon_texture": "pixieIcon",
        "icon_mask_texture": "pixieIconColorMask",
        "style": "pixie",
    },

    "SahilP > YukataZoe": {
        "color_texture": "zoeColor",
        "color_mask_texture": "zoeColorMask",
        "head_mesh": "zoeHead",
        "hand_mesh": "kronkHand",
        "torso_mesh": "kronkTorso",
        "pelvis_mesh": "bearPelvis",
        "upper_arm_mesh": "cyborgUpperArm",
        "forearm_mesh": "wizardForeArm",
        "upper_leg_mesh": "agentUpperLeg",
        "lower_leg_mesh": "wizardLowerLeg",
        "toes_mesh": "zoeToes",
        "jump_sounds": ["zoeJump01", "zoeJump02", "zoeJump03"],
        "attack_sounds": ["zoeAttack01", "zoeAttack02", "zoeAttack03"],
        "impact_sounds": ["zoeImpact01", "zoeImpact02", "zoeImpact03", "zoeImpact04"],
        "death_sounds": ["zoeDeath01"],
        "pickup_sounds": ["zoePickup01"],
        "fall_sounds": ["zoeFall01"],
        "icon_texture": "zoeIcon",
        "icon_mask_texture": "zoeIconColorMask",
        "style": "female",
    },

    "SahilP > WeddingPixie": {
        "color_texture": "pixieColor",
        "color_mask_texture": "pixieColorMask",
        "head_mesh": "pixieHead",
        "hand_mesh": "pixieHand",
        "torso_mesh": "pixieTorso",
        "pelvis_mesh": "pixiePelvis",
        "upper_arm_mesh": "wizardUpperArm",
        "forearm_mesh": "wizardForeArm",
        "upper_leg_mesh": "bunnyUpperLeg",
        "lower_leg_mesh": "pixieLowerLeg",
        "toes_mesh": "pixieToes",
        "jump_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "attack_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "impact_sounds": ["pixieHit1", "pixieHit2"],
        "death_sounds": ["pixieDeath"],
        "pickup_sounds": ["pixie1", "pixie2", "pixie3", "pixie4"],
        "fall_sounds": ["pixieFall"],
        "icon_texture": "pixieIcon",
        "icon_mask_texture": "pixieIconColorMask",
        "style": "pixie",
    },
}


def register_character(name, body):
    t = Appearance(name)
    t.color_texture = body["color_texture"]
    t.color_mask_texture = body["color_mask_texture"]
    t.default_color = (0, 1, 0.7)
    t.default_highlight = (0.65, 0.35, 0.75)
    t.icon_texture = body["icon_texture"]
    t.icon_mask_texture = body["icon_mask_texture"]
    t.head_mesh = body["head_mesh"]
    t.torso_mesh = body["torso_mesh"]
    t.pelvis_mesh = body["pelvis_mesh"]
    t.upper_arm_mesh = body["upper_arm_mesh"]
    t.forearm_mesh = body["forearm_mesh"]
    t.hand_mesh = body["hand_mesh"]
    t.upper_leg_mesh = body["upper_leg_mesh"]
    t.lower_leg_mesh = body["lower_leg_mesh"]
    t.toes_mesh = body["toes_mesh"]
    t.attack_sounds = body["attack_sounds"]
    t.jump_sounds = body["jump_sounds"]
    t.impact_sounds  = body["impact_sounds"]
    t.death_sounds = body["death_sounds"]
    t.pickup_sounds = body["pickup_sounds"]
    t.fall_sounds = body["fall_sounds"]
    t.style = body["style"]


def register_characters():
    for name, body in CHARACTERS.items():
        register_character(name, body)


# ba_meta export plugin
class Main(babase.Plugin):
    def on_app_running(self):
        register_characters()

